import { Geist, Geist_Mono } from "next/font/google";
import { Raleway } from 'next/font/google';
import Footer from "./components/Footer/Footer";
import Socillinks from "./components/sociallinks/Socillinks";
import "./globals.css";


const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-raleway',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
        <Footer />
        <div className="md:block hidden">
          <Socillinks />
        </div>
      </body>
    </html>
  );
}
